package tw.saietf.app

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class BuildContractTest {
    @Test
    fun `installed app exposes the approved identity and locale`() {
        assertEquals("tw.saietf.app", BuildConfig.APPLICATION_ID)
        assertEquals("1.1.29", BuildConfig.VERSION_NAME)
        assertEquals(10129, BuildConfig.VERSION_CODE)
        assertEquals("zh-Hant-TW", SaiEtfApplication.DEFAULT_LOCALE_TAG)
    }

    @Test
    fun `build graph contains every approved module`() {
        assertEquals(
            setOf(
                ":app",
                ":core:model",
                ":core:finance",
                ":core:database",
                ":core:market",
                ":core:designsystem",
                ":feature:dashboard",
                ":feature:portfolios",
                ":feature:transactions",
                ":feature:dividends",
                ":feature:editor",
                ":feature:settings",
                ":platform:surfaces",
            ),
            BuildContract.includedModules,
        )
    }

    @Test
    fun `v1069 keeps completed formal UI instrument page and upgrade contracts`() {
        val manifest = File("src/main/AndroidManifest.xml").readText()
        val activity = File("src/main/kotlin/tw/saietf/app/MainActivity.kt").readText()
        val application = File("src/main/kotlin/tw/saietf/app/SaiEtfApplication.kt").readText()
        val gradle = File("build.gradle.kts").readText()
        val styles = File("src/main/res/values/styles.xml").readText()
        val providers = File("src/main/kotlin/tw/saietf/app/AndroidMarketProviders.kt").readText()
        val taiwanProfiles = File("src/main/kotlin/tw/saietf/app/TaiwanInstrumentInfoProvider.kt").readText()
        val dailyHistory = File("src/main/kotlin/tw/saietf/app/TaiwanDailyHistoryProvider.kt").readText()
        val kLineView = File("src/main/kotlin/tw/saietf/app/TaiwanKLineView.kt").readText()
        val indicators = File("src/main/kotlin/tw/saietf/app/TaiwanTechnicalIndicators.kt").readText()
        val institutional = File("src/main/kotlin/tw/saietf/app/TaiwanInstitutionalProvider.kt").readText()
        val revenue = File("src/main/kotlin/tw/saietf/app/TaiwanRevenueProvider.kt").readText()
        val capitalMetrics = File("src/main/kotlin/tw/saietf/app/TaiwanCapitalMetrics.kt").readText()
        val marketModels = File("../core/market/src/main/kotlin/tw/saietf/core/market/MarketModels.kt").readText()
        val marketProviderV2 = File("../core/market/src/main/kotlin/tw/saietf/core/market/MarketDataProviderV2.kt").readText()
        val hotStore = File("../core/market/src/main/kotlin/tw/saietf/core/market/MemoryMarketStore.kt").readText()
        val marketCenter = File("../core/market/src/main/kotlin/tw/saietf/core/market/MarketDataCenter.kt").readText()
        val fugleProvider = File("src/main/kotlin/tw/saietf/app/FugleWebSocketProvider.kt").readText()
        val fugleKeyStore = File("src/main/kotlin/tw/saietf/app/FugleApiKeyStore.kt").readText()
        val fugleController = File("src/main/kotlin/tw/saietf/app/FugleStreamingController.kt").readText()
        val arbitrator = File("../core/market/src/main/kotlin/tw/saietf/core/market/MarketArbitrator.kt").readText()
        val circuitBreaker = File("../core/market/src/main/kotlin/tw/saietf/core/market/ProviderCircuitBreaker.kt").readText()
        val marketPersistence = File("src/main/kotlin/tw/saietf/app/MarketPersistenceRepository.kt").readText()
        val persistenceController = File("src/main/kotlin/tw/saietf/app/MarketPersistenceController.kt").readText()
        val database = File("../core/database/src/main/kotlin/tw/saietf/core/database/SaiEtfDatabase.kt").readText()
        val marketCacheDao = File("../core/database/src/main/kotlin/tw/saietf/core/database/dao/MarketCacheDao.kt").readText()
        val stockDetailRepository = File("src/main/kotlin/tw/saietf/app/StockDetailRepository.kt").readText()
        val stockDetailDao = File("../core/database/src/main/kotlin/tw/saietf/core/database/dao/StockDetailDao.kt").readText()
        val sessionPolicy = File("src/main/kotlin/tw/saietf/app/TaiwanIntradaySessionPolicy.kt").readText()
        val technicalEngine = File("src/main/kotlin/tw/saietf/app/TaiwanTechnicalEngine.kt").readText()

        assertTrue(manifest.contains("android:name=\".MainActivity\""))
        assertTrue(manifest.contains("android:exported=\"true\""))
        assertTrue(manifest.contains("android.intent.action.MAIN"))
        assertTrue(manifest.contains("android.intent.category.LAUNCHER"))
        assertTrue(manifest.contains("android.permission.INTERNET"))
        assertTrue(activity.contains("showTradeDialog"))
        assertTrue(activity.contains("ledgerRepository"))
        assertTrue(activity.contains("performanceHistoryRepository"))
        assertTrue(activity.contains("showDailyPerformanceDialog"))
        assertTrue(activity.contains("PortfolioTrendView"))
        assertTrue(activity.contains("TrendRange.WEEK"))
        assertTrue(activity.contains("TrendRange.MONTH"))
        assertTrue(activity.contains("TrendRange.YEAR"))
        assertTrue(activity.contains("09:00"))
        assertTrue(activity.contains("13:30"))
        assertTrue(activity.contains("showTransactionHistoryDialog"))
        assertTrue(activity.contains("pageBuyCount"))
        assertTrue(activity.contains("pageSellCount"))
        assertTrue(activity.contains("pageGrossAmount"))
        assertTrue(activity.contains("showEditTransactionDialog"))
        assertTrue(activity.contains("showDeleteTransactionConfirmation"))
        assertTrue(activity.contains("repository.correctTrade"))
        assertTrue(activity.contains("repository.deleteTrade"))
        assertTrue(activity.contains("修改 / 刪除採 Ledger 修正紀錄"))
        assertTrue(activity.contains("原始 Ledger 稽核軌跡"))
        assertTrue(activity.contains("來源保護"))
        assertTrue(activity.contains("同步策略：Fugle WebSocket → TWSE MIS → Yahoo"))
        assertTrue(activity.contains("providerHealth"))
        assertTrue(marketModels.contains("MarketSource.FUGLE") || marketModels.contains("FUGLE"))
        assertTrue(!marketModels.contains("SHIOAJI"))
        assertTrue(!activity.contains("Shioaji"))
        assertTrue(application.contains("removeRetiredShioajiSecrets"))
        assertTrue(application.contains("saietf-shioaji-gateway"))
        assertTrue(application.contains("deleteEntry(\"saietf-shioaji-gateway-token-v1\")"))
        assertTrue(marketModels.contains("QuoteQuality"))
        assertTrue(marketModels.contains("fallbackLevel"))
        assertTrue(marketModels.contains("sourceTimestampEpochMillis"))
        assertTrue(marketProviderV2.contains("interface MarketDataProvider"))
        assertTrue(marketProviderV2.contains("MarketProviderCapability.STREAM") || marketProviderV2.contains("STREAM"))
        assertTrue(marketProviderV2.contains("PollingMarketDataProviderAdapter"))
        assertTrue(hotStore.contains("MutableStateFlow"))
        assertTrue(hotStore.contains("StateFlow<Map<String, MarketQuote>>"))
        assertTrue(marketCenter.contains("val quotesState = hotStore.quotes"))
        assertTrue(marketCenter.contains("acceptStreamingQuote"))
        assertTrue(marketCenter.contains("MarketSource.FUGLE"))
        assertTrue(fugleProvider.contains("wss://api.fugle.tw/marketdata/v1.0/stock/streaming"))
        assertTrue(fugleProvider.contains("\"heartbeat\""))
        assertTrue(fugleProvider.contains("\"ping\""))
        assertTrue(fugleProvider.contains("\"subscribe\""))
        assertTrue(fugleProvider.contains("\"unsubscribe\""))
        assertTrue(fugleProvider.contains("replaceSubscriptions"))
        assertTrue(fugleProvider.contains("HEARTBEAT_TIMEOUT_MILLIS"))
        assertTrue(fugleProvider.contains("scheduleReconnect"))
        assertTrue(fugleKeyStore.contains("AndroidKeyStore"))
        assertTrue(fugleKeyStore.contains("AES/GCM/NoPadding"))
        assertTrue(fugleController.contains("acceptStreamingQuote"))
        assertTrue(arbitrator.contains("ArbitrationReason"))
        assertTrue(arbitrator.contains("REJECT_OUT_OF_ORDER_SEQUENCE"))
        assertTrue(arbitrator.contains("REJECT_OLDER_SESSION"))
        assertTrue(arbitrator.contains("ACCEPT_NEWER_TIMESTAMP"))
        assertTrue(arbitrator.contains("MarketSource.FUGLE to 0"))
        assertTrue(circuitBreaker.contains("ProviderCircuitState.RECOVERING"))
        assertTrue(circuitBreaker.contains("recordFailure"))
        assertTrue(circuitBreaker.contains("recordSuccess"))
        assertTrue(marketCenter.contains("arbitrator.decide"))
        assertTrue(marketCenter.contains("circuitBreaker"))
        assertTrue(activity.contains("circuitState.name"))
        assertTrue(activity.contains("quote.sequence"))
        assertTrue(activity.contains("quote.fallbackLevel"))
        assertTrue(activity.contains("bindMarketStateFlow"))
        assertTrue(activity.contains("marketDataCenter.quotesState.collectLatest"))
        assertTrue(activity.contains("marketPersistenceController.flushNow"))
        assertTrue(marketPersistence.contains("MarketQuoteSnapshotEntity"))
        assertTrue(marketPersistence.contains("MarketMinuteCandleEntity"))
        assertTrue(persistenceController.contains("PERSIST_INTERVAL_MILLIS = 5_000L"))
        assertTrue(database.contains("version = 5"))
        assertTrue(database.contains("MIGRATION_3_4"))
        assertTrue(database.contains("MIGRATION_4_5"))
        assertTrue(marketCacheDao.contains("upsertSnapshots"))
        assertTrue(marketCacheDao.contains("upsertCandles"))
        assertTrue(stockDetailRepository.contains("StockDetailDataset"))
        assertTrue(stockDetailRepository.contains("canonicalRevision"))
        assertTrue(stockDetailRepository.contains("needsRefresh"))
        assertTrue(stockDetailDao.contains("observeInstitutional"))
        assertTrue(stockDetailDao.contains("observeMonthlyRevenue"))
        assertTrue(stockDetailDao.contains("observeEtfComponents"))
        assertTrue(stockDetailDao.contains("observeDividendReference"))
        assertTrue(sessionPolicy.contains("LocalTime.of(9, 0)"))
        assertTrue(sessionPolicy.contains("minuteBucketEnd"))
        assertTrue(sessionPolicy.contains("closeGraceEndEpochMillis"))
        assertTrue(technicalEngine.contains("fun sma"))
        assertTrue(technicalEngine.contains("fun ema"))
        assertTrue(technicalEngine.contains("fun rsi"))
        assertTrue(technicalEngine.contains("fun macd"))
        assertTrue(activity.contains("private enum class MainTab"))
        assertTrue(activity.contains("buildBottomNavigation"))
        assertTrue(activity.contains("setLineSpacing(0f, 1.08f)"))
        assertTrue(activity.contains("dp(48)"))
        assertTrue(activity.contains("SaiTheme.BRAND_SOFT"))
        assertTrue(activity.contains("bottomNavigation.getChildAt(index) as? TextView"))
        assertTrue(activity.contains("radiusDp = 17f"))
        assertTrue(activity.contains("切換至"))
        assertTrue(activity.contains("installBackNavigation"))
        assertTrue(activity.contains("OnBackPressedCallback"))
        assertTrue(activity.contains("onBackPressedDispatcher"))
        assertTrue(activity.contains("instrumentTabButtons"))
        assertTrue(activity.contains("updateInstrumentTabSelection"))
        assertTrue(activity.contains("OnBackPressedCallback"))
        assertTrue(activity.contains("onBackPressedDispatcher.addCallback"))
        assertTrue(activity.contains("renderMainTab"))
        assertTrue(activity.contains("renderHomePage"))
        assertTrue(activity.contains("buildHomeQuickActions"))
        assertTrue(activity.contains("首頁快速操作：新增交易、持股分析、持股清單、行情牆"))
        assertTrue(activity.contains("cardText(value, 26f"))
        assertTrue(activity.contains("LinearLayout.LayoutParams(dp(4), dp(18))"))
        assertTrue(activity.contains("setLineSpacing(0f, 1.08f)"))
        assertTrue(activity.contains("renderMarketPage"))
        assertTrue(activity.contains("renderTradePage"))
        assertTrue(activity.contains("renderDividendPage"))
        assertTrue(activity.contains("renderSettingsPage"))
        assertTrue(activity.contains("showThemeSettingsDialog"))
        assertTrue(activity.contains("currentThemeSummary"))
        assertTrue(activity.contains("toggleDayNightTheme"))
        assertTrue(activity.contains("切換日間模式"))
        assertTrue(activity.contains("切換夜間模式"))
        assertTrue(activity.contains("SaiTheme.HINT"))
        assertTrue(activity.contains("SaiTheme.ON_ACCENT"))
        assertTrue(activity.contains("SaiTheme.TEXT_SECONDARY"))
        assertTrue(activity.contains("SaiTheme.Mode.SYSTEM"))
        assertTrue(activity.contains("applyThemeToWindow"))
        assertTrue(activity.contains("R.style.Theme_SaiETF_Dark"))
        assertTrue(activity.contains("setTheme(if (darkTheme)"))
        assertTrue(styles.contains("Theme.SaiETF.Dark"))
        assertTrue(styles.contains("android:windowLightStatusBar\">false"))
        assertEquals(2, "android:forceDarkAllowed\">false".toRegex().findAll(styles).count())
        assertTrue(activity.contains("UI_MODE_NIGHT_YES"))
        assertTrue(activity.contains("buildSettingsStatusCard"))
        assertTrue(activity.contains("contentDescription = \"\$title，\$description，可點擊\""))
        assertTrue(activity.contains("cardText(\"›\", 22f, SaiTheme.BRAND)"))
        assertTrue(activity.contains("cardText(\"›\", 22f, SaiTheme.ON_ACCENT)"))
        assertTrue(activity.contains("▌  "))
        assertTrue(activity.contains("區段："))
        assertTrue(activity.contains("●  "))
        assertTrue(activity.contains("台股資產管家  •"))
        assertTrue(activity.contains("\"新增交易\" to { showTradeDialog() }"))
        assertTrue(activity.contains("buildPrimaryActionCard(\n                title = \"行情牆\""))
        assertTrue(activity.contains("sectionTitle(\"帳務工具\")"))
        assertTrue(activity.contains("buildPrimaryActionCard(\"股息中心\""))
        assertTrue(activity.contains("\"版本 / 資料庫\""))
        assertTrue(activity.contains("\"即時行情\""))
        assertTrue(activity.contains("首頁次要指標：帳務投入成本與持股檔數"))
        assertTrue(activity.contains("排序方式｜再點目前項目切換升降冪"))
        assertTrue(activity.contains("最近交易｜最多 5 筆"))
        assertTrue(activity.contains("查看完整交易紀錄 ›"))
        assertTrue(activity.contains("股息現金流"))
        assertTrue(activity.contains("本月已確認"))
        assertTrue(activity.contains("sectionTitle(\"資料\")"))
        assertTrue(activity.contains("sectionTitle(\"系統與維護\")"))
        assertTrue(!activity.contains("sectionTitle(\"資料與系統\")"))
        assertTrue(activity.contains("ACCESSIBILITY_LIVE_REGION_POLITE"))
        assertTrue(activity.contains("IMPORTANT_FOR_ACCESSIBILITY_YES"))
        assertTrue(activity.contains("minimumHeight = displayDp(44)"))
        assertTrue(activity.contains("setDashboardPnlText"))
        assertTrue(activity.contains("numericValue > 0.0 -> SaiTheme.GAIN"))
        assertTrue(activity.contains("numericValue < 0.0 -> SaiTheme.LOSS"))
        assertTrue(activity.contains("else -> SaiTheme.PNL_FLAT"))
        assertTrue(activity.contains("目前頁面"))
        assertTrue(activity.contains("isSelected = active"))
        assertTrue(activity.contains("目前分頁"))
        assertTrue(activity.contains("切換個股資訊："))
        assertTrue(activity.contains("已是第一檔"))
        assertTrue(activity.contains("已是最後一檔"))
        assertTrue(activity.contains("contentDescription = \"返回"))
        assertTrue(!activity.contains("dp(44)"))
        assertTrue(!activity.contains("dp(46)"))
        assertTrue(activity.contains("\"交易代號\""))
        assertTrue(activity.contains("\"交易成交價\""))
        assertTrue(activity.contains("\"交易股數\""))
        assertTrue(activity.contains("addView(symbol)\n            addView(price)\n            addView(shares)"))
        assertTrue(activity.contains("系統摘要"))
        assertTrue(activity.contains("SaiTheme.softCard"))
        assertTrue(activity.contains("loadTradePreview"))
        assertTrue(activity.contains("buildTradePreviewCard"))
        assertTrue(activity.contains("if (isBuy) SaiTheme.GAIN else SaiTheme.LOSS"))
        assertTrue(activity.contains("SaiTheme.CARD_SOFT"))
        assertTrue(activity.contains("已修改"))
        assertTrue(activity.contains("最近交易"))
        assertTrue(activity.contains("loadDividendPreview"))
        assertTrue(activity.contains("buildDividendEventCard"))
        assertTrue(activity.contains("SaiTheme.softCard"))
        assertTrue(activity.contains("if (confirmed) \"已確認\" else \"預告\""))
        assertTrue(activity.contains("SaiTheme.ACCENT_SOFT"))
        assertTrue(activity.contains("本月摘要"))
        assertTrue(activity.contains("今年已確認"))
        assertTrue(activity.contains("系統與維護"))
        assertTrue(activity.contains("Room v5"))
        assertTrue(activity.contains("fitsSystemWindows = true"))
        assertTrue(activity.contains("homeHoldingsContainer"))
        assertTrue(activity.contains("marketQuotesContainer"))
        assertTrue(activity.contains("renderHomeHoldingsInline"))
        assertTrue(activity.contains("buildHoldingSummaryCard"))
        assertTrue(activity.contains("totalPnl > 0.0 -> SaiTheme.GAIN"))
        assertTrue(activity.contains("else -> SaiTheme.LOSS"))
        assertTrue(activity.contains("總損益 \$pnlText"))
        assertTrue(activity.contains("cardText(\"現價\", 10f, SaiTheme.MUTED)"))
        assertTrue(activity.contains("持有 \$shares 股  •  市值 \$marketValue"))
        assertTrue(activity.contains("buildInlineMarketSortBar"))
        assertTrue(activity.contains("buildMarketColumnHeader"))
        assertTrue(activity.contains("行情欄位：商品、價格、漲跌幅"))
        assertTrue(activity.contains("marketWallDescending"))
        assertTrue(activity.contains("SaiTheme.BRAND_SOFT"))
        assertTrue(activity.contains("\"  ↓\""))
        assertTrue(activity.contains("\"  ↑\""))
        assertTrue(activity.contains("renderMarketQuotesInline"))
        assertTrue(activity.contains("buildMarketQuoteCard"))
        assertTrue(activity.contains("SaiTheme.GAIN"))
        assertTrue(activity.contains("SaiTheme.LOSS"))
        assertTrue(activity.contains("SaiTheme.FLAT"))
        assertTrue(activity.contains("contentDescription ="))
        assertTrue(activity.contains("refreshVisibleMarketSections"))
        assertTrue(activity.contains("showInstrumentPage"))
        assertTrue(activity.contains("SaiTheme.BRAND_SOFT"))
        assertTrue(activity.contains("radiusDp = 14f"))
        assertTrue(activity.contains("instrumentTabContentView"))
        assertTrue(activity.contains("contentDescription = \"狀態：\$value\""))
        assertTrue(activity.contains("setLineSpacing(0f, 1.08f)"))
        assertTrue(activity.contains("selectInstrumentPageTab"))
        assertTrue(activity.contains("ensureInstrumentPageData"))
        assertTrue(activity.contains("loadInstrumentProfileForPage"))
        assertTrue(activity.contains("loadInstrumentHistoryForPage"))
        assertTrue(activity.contains("loadInstrumentInstitutionalForPage"))
        assertTrue(activity.contains("loadInstrumentRevenueForPage"))
        assertTrue(activity.contains("renderInstrumentPageTab"))
        assertTrue(activity.contains("TaiwanTechnicalEngine.macd"))
        assertTrue(activity.contains("receivedAtEpochMillis"))
        assertTrue(activity.contains("showFugleSettingsDialog"))
        assertTrue(activity.contains("fugleStreamingController.updateSymbols"))
        assertTrue(activity.contains("fugleStreamingController.pause"))
        assertTrue(activity.contains("showDividendCenter"))
        assertTrue(activity.contains("DatePickerDialog"))
        assertTrue(activity.contains("showBackupCenter"))
        assertTrue(activity.contains("ACTION_CREATE_DOCUMENT"))
        assertTrue(activity.contains("ACTION_OPEN_DOCUMENT"))
        assertTrue(activity.contains("showHoldingsAnalysisDialog"))
        assertTrue(activity.contains("Top 3"))
        assertTrue(activity.contains("MarketWallMode.DETAIL_LIST"))
        assertTrue(activity.contains("MarketWallMode.LARGE_LIST"))
        assertTrue(activity.contains("MarketWallMode.GRID"))
        assertTrue(activity.contains("MarketWallMode.MULTI_TREND"))
        assertTrue(activity.contains("MarketWallMode.TREND_SIGNAL"))
        assertTrue(activity.contains("chunked(3)"))
        assertTrue(activity.contains("MarketWallSort.CHANGE_PCT"))
        assertTrue(activity.contains("marketWallDialog?.isShowing == true"))
        assertTrue(activity.contains("controls.removeAllViews()"))
        assertTrue(activity.contains("marketWallMode"))
        assertTrue(activity.contains("marketWallSort"))
        assertTrue(activity.contains("marketWallDescending"))
        assertTrue(activity.contains("marketWallRender"))
        assertTrue(activity.contains("marketWallRender?.invoke()"))
        assertTrue(activity.contains("marketWallDialog?.dismiss()"))
        assertTrue(activity.contains("holdingDetailDialog?.dismiss()"))
        assertTrue(activity.contains("holdingDetailDialog = dialog"))
        assertTrue(activity.contains("setPositiveButton(\"寫入 Ledger\", null)"))
        assertTrue(activity.contains("setPositiveButton(\"儲存\", null)"))
        assertTrue(activity.contains("toLongOrNull()"))
        assertTrue(activity.contains("toDoubleOrNull()"))
        assertTrue(activity.contains("val tradeDate = dateInput(\"交易日期\""))
        assertTrue(activity.contains("交易日期不可晚於今天"))
        assertTrue(activity.contains("availableShares"))
        assertTrue(activity.contains("selectedSide == LedgerEntryKind.SELL"))
        assertTrue(activity.contains("超過目前持有"))
        assertTrue(activity.contains("股權登記日不可早於除息日"))
        assertTrue(activity.contains("發放日不可早於股權登記日"))
        assertTrue(activity.contains("saveButton.isEnabled = false"))
        assertTrue(activity.contains("saveButton.isEnabled = true"))
        assertTrue(activity.contains("performanceDialog?.dismiss()"))
        assertTrue(activity.contains("performanceDialogContent = null"))
        assertTrue(activity.contains("每日損益紀錄"))
        assertTrue(activity.contains("render.records"))
        assertTrue(activity.contains("takeLast(12)"))
        assertTrue(activity.contains("showHoldingSelectorDialog"))
        assertTrue(activity.contains("showHoldingDetailDialog"))
        assertTrue(activity.contains("平均成本") || activity.contains("\"均價\""))
        assertTrue(activity.contains("InstrumentInfoTab"))
        assertTrue(activity.contains("buildInstrumentMetricCard"))
        assertTrue(activity.contains("buildInstrumentQuoteStrip"))
        assertTrue(activity.contains("contentDescription = \"標的即時行情：\$symbol\""))
        assertTrue(activity.contains("cardText(\"即時行情\", 10f, SaiTheme.BRAND)"))
        assertTrue(activity.contains("即時行情摘要"))
        assertTrue(activity.contains("\"均價\""))
        assertTrue(activity.contains("\"市值\""))
        assertTrue(activity.contains("InstrumentInfoTab.COMPONENTS"))
        assertTrue(activity.contains("EtfComponentDonutView"))
        assertTrue(activity.contains("個股不適用 ETF 成分"))
        assertTrue(activity.contains("InstrumentInfoTab.FINANCIAL"))
        assertTrue(activity.contains("taiwanInstrumentInfoProvider"))
        assertTrue(activity.contains("台股基本資料"))
        assertTrue(activity.contains("實收資本額"))
        assertTrue(taiwanProfiles.contains("openapi.twse.com.tw"))
        assertTrue(taiwanProfiles.contains("tpex.org.tw"))
        assertTrue(taiwanProfiles.contains("公司代號"))
        assertTrue(taiwanProfiles.contains("實收資本額"))
        assertTrue(taiwanProfiles.contains("issuedCommonShares"))
        assertTrue(taiwanProfiles.contains("已發行普通股數"))
        assertTrue(activity.contains("已發行普通股"))
        assertTrue(activity.contains("公司聯絡資料"))
        assertTrue(activity.contains("taiwanDailyHistoryProvider"))
        assertTrue(activity.contains("TaiwanKLineView"))
        assertTrue(activity.contains("日 K｜近 1 年真實歷史資料"))
        assertTrue(dailyHistory.contains("interval=1d&range=1y"))
        assertTrue(dailyHistory.contains("TaiwanDailyBar"))
        assertTrue(kLineView.contains("drawRect"))
        assertTrue(indicators.contains("sma5"))
        assertTrue(indicators.contains("rsi14"))
        assertTrue(activity.contains("MA5"))
        assertTrue(activity.contains("RSI14"))
        assertTrue(activity.contains("20 日均量"))
        assertTrue(activity.contains("taiwanInstitutionalProvider"))
        assertTrue(activity.contains("三大法人"))
        assertTrue(institutional.contains("TWSE 三大法人 T86"))
        assertTrue(institutional.contains("TPEx 三大法人"))
        assertTrue(institutional.contains("foreignNetShares"))
        assertTrue(activity.contains("taiwanRevenueProvider"))
        assertTrue(activity.contains("月營收"))
        assertTrue(revenue.contains("t187ap05_L"))
        assertTrue(revenue.contains("mopsfin_t187ap05_O"))
        assertTrue(revenue.contains("yearOverYearPct"))
        assertTrue(capitalMetrics.contains("marketCapitalizationTwd"))
        assertTrue(capitalMetrics.contains("oneYearReturnPct"))
        assertTrue(activity.contains("公司資本 / 市值"))
        assertTrue(activity.contains("現價 × 已發行普通股"))
        assertTrue(taiwanProfiles.contains("issuedCommonShares"))
        assertTrue(taiwanProfiles.contains("已發行普通股數"))
        assertTrue(activity.contains("已發行普通股"))
        assertTrue(activity.contains("公司聯絡資料"))
        assertTrue(activity.contains("上一檔"))
        assertTrue(activity.contains("下一檔"))
        assertTrue(activity.contains("latestAsOf"))
        assertTrue(activity.contains("advancingCount"))
        assertTrue(activity.contains("decliningCount"))
        assertTrue(activity.contains("unchangedCount"))
        assertTrue(activity.contains("已要求行情中心立即刷新"))
        assertTrue(activity.contains("monthEstimated"))
        assertTrue(activity.contains("monthConfirmed"))
        assertTrue(activity.contains("monthConfirmedRows"))
        assertTrue(activity.contains("monthAnnouncedRows"))
        assertTrue(activity.contains("monthConfirmedCash"))
        assertTrue(activity.contains("showDividendCalendarDialog"))
        assertTrue(activity.contains("YearMonth.now"))
        assertTrue(activity.contains("本月目前沒有股息事件"))
        assertTrue(activity.contains("backupRepository.inspectJson"))
        assertTrue(activity.contains("confirmBackupRestore"))
        assertTrue(activity.contains("目前帳務非空"))
        assertTrue(activity.contains("restoreButton.isEnabled = !hasExistingLedger"))
        assertTrue(activity.contains("交易、持股、股息、行情憑證與本機帳務資料都不會變更"))
        assertTrue(activity.contains("SHA-256"))
        assertTrue(activity.contains("showDisplaySettingsDialog"))
        assertTrue(activity.contains("displayScale"))
        assertTrue(activity.contains("saietf-display"))
        assertTrue(activity.contains("showSpacingSettingsDialog"))
        assertTrue(activity.contains("displaySpacingScale"))
        assertTrue(activity.contains("displayDp"))
        assertTrue(activity.contains("showSystemStatusDialog"))
        assertTrue(activity.contains("requestImmediateMarketRefresh"))
        assertTrue(activity.contains("showResetDisplaySettingsConfirmation"))
        assertTrue(activity.contains("確認恢復"))
        assertTrue(activity.contains("已要求行情中心立即更新"))
        assertTrue(activity.contains("系統狀態 / 診斷"))
        assertTrue(activity.contains("行情覆蓋"))
        assertTrue(activity.contains("quoteAgeSeconds"))
        assertTrue(activity.contains("staleSymbols"))
        assertTrue(activity.contains("showQuoteDiagnosticsDialog"))
        assertTrue(activity.contains("行情來源 / 品質診斷"))
        assertTrue(activity.contains("複製診斷"))
        assertTrue(activity.contains("setPrimaryClip"))
        assertTrue(!activity.contains("showMarketWall(option, sort, descending)"))
        assertTrue(activity.contains("listOf(10, 20, 50)"))
        assertTrue(providers.contains("YahooIntradayHistoryProvider"))
        assertTrue(providers.contains("interval=1m"))
        assertTrue(providers.contains("TaiwanSecurityNameCache"))
        assertTrue(providers.contains("TaiwanSecurityNameCache.remember"))
        assertTrue(providers.contains("val localizedNames = TaiwanSecurityNameCache.resolve(symbols)"))
        assertTrue(providers.contains("name = localizedName?.trim()"))
        assertTrue(!providers.contains("meta.optString(\"longName\")"))
        assertTrue(!providers.contains("meta.optString(\"shortName\")"))
        assertTrue(gradle.contains("saietf-development.jks"))
    }

    @Test
    fun `third stage exposes real ledger entry and truthful market placeholders`() {
        assertEquals("SaiETF 資產管家", FirstVersionContract.appDisplayName)
        assertEquals("第六十階段 1.0.69｜正式 UI 完整合流｜五大頁面・個股 8 Tab・即時狀態", FirstVersionContract.releaseLine)
        assertEquals("首頁｜行情｜交易｜股息｜設定｜個股 8 Tab｜StateFlow｜Finance Lock 不變", FirstVersionContract.phaseLine)
        assertEquals(
            listOf("總資產", "帳務投入成本", "昨日 / 今日 / 總損益", "持股檔數"),
            FirstVersionContract.dashboardMetrics.map { it.title },
        )
        assertEquals(
            listOf("交易新增", "交易紀錄", "持股分析", "持股清單", "行情牆", "股息", "資料備份", "顯示設定", "卡片間距", "系統狀態", "Fugle 即時行情", "立即更新行情", "介面恢復標準"),
            FirstVersionContract.landingCards.map { it.title },
        )
        assertTrue(
            FirstVersionContract.dashboardMetrics
                .single { it.title == "總資產" }
                .note
                .contains("禁止用部分報價冒充總資產"),
        )
        assertTrue(
            FirstVersionContract.landingCards
                .single { it.title == "交易新增" }
                .status
                .contains("Ledger Repository"),
        )
    }
}
